---

- name: Users
  no_log: true
  user:
    name: "{{ item.key }}"
    state: present
    password: "{{ item.value.password|password_hash('sha512') }}"
    update_password: on_create
    home: "{{ item.value.home | default(omit) }}"
    createhome: yes
  with_dict: "{{ ftp_users }}"

- name: Install
  apt:
    pkg: proftpd-basic
    state: present

- name: Configure
  template:
    src: etc/proftpd/proftpd.conf
    dest: /etc/proftpd/proftpd.conf
  notify: Restart Proftpd

- name: Enable
  service:
    name: proftpd
    state: started
    enabled: true
